# configs/mlflow_config.yaml

experiment_name: "Quant_Trading_Main"
tracking_uri: "file:./mlruns"   # Change to "http://<EC2-IP>:5000" for cloud tracking
artifact_location: "./mlruns/artifacts"

tags:
  project: "Causal-DRL-Hedging"
  phase: "Research"
  data_source: "kdb_tick"